Home cards
BCcampus/open-sage pull request #46
Opened 2019-02-01 00:11 UTC by alex-418

Resolves #7

2019-02-01 18:26 UTC, bdolor requested changes

2019-02-01 18:26 UTC, bdolor commented on app/Controllers/FrontPage.php
> +		return $id;
I think we should return `intval($id)`

2019-02-01 18:26 UTC, bdolor commented on resources/assets/styles/common/_global.scss
> +  background: $color_blue-navy;
change `$color_blue-navy` to `$color-blue-navy`

2019-02-01 18:26 UTC, bdolor commented on resources/assets/styles/common/_global.scss
> +    background: $color_black;
change `$color_black` to `$color-black`

2019-02-01 18:26 UTC, bdolor commented on resources/assets/styles/components/_featured.scss
> +  article:first-of-type {
I remember this turning into a rat's nest to untangle when things like the number of boxes changed, or when switching to mobile view and boxes were misaligned. `no-gutter` could be explored or another edge to edge class that won't create more work for us down the road.

2019-02-01 18:26 UTC, bdolor commented on resources/assets/styles/components/_featured.scss
> +    margin: 0;
I recommend using bootstrap classes to control margin and padding at the element class.

2019-02-01 18:26 UTC, bdolor commented on resources/assets/styles/components/_featured.scss
> +    background-color: $color-grey-light;
would be better to create a class called `.bkgd-grey-light` that isn't tied to `.homepage-cards` in case we want to re-use it somewhere

2019-02-01 18:26 UTC, bdolor commented on resources/views/front-page.blade.php
>  		@include('partials.front-page-hero')
I'd like to see: 
```
        <div class="row">
		    @include('partials.front-page-hero')
        </div>
        <div class="row">
        @include('partials.front-page-cards')
        </div>
```

2019-02-01 18:26 UTC, bdolor commented on resources/assets/styles/components/_featured.scss
> +    color: $color-white;
remove `color: $color-white` and create/define `.text-inverse` as is called in the element

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +                    <h4 itemprop="name" class="blue-bkgd text-inverse col-sm mt-auto text-center">{{get_the_title($get_left_card_id)}}
define `.text-inverse` as per note above

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +                <div class="featured-topic row-fluid d-flex" style="background-image: url({!! get_the_post_thumbnail_url($get_left_card_id) !!});">
would like to see a function similar to `getThumb` in bcc-sage that guarantees the delivery of at least a placeholder image

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +            <meta itemprop="author" content="{{get_post_field('post_author', $get_left_card_id)}}"/>
`post_author` returns a number and fails structured data validation.

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +					<meta itemprop="url" content="https://bccampus.ca/wp-content/themes/bcc-sage/dist/images/bccampus-logo.png"/>
wonder if we should port over a bcccampus logo to this theme? Benefit would be if it ever changes, we would contain the effect of a broken image path...

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +                @if (has_excerpt($get_right_card_id))
we could move logic out of blade template and into `App.php` for re-use elsewhere

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +                <a class="btn btn-primary mb-3" href="{{ get_permalink($get_right_card_id) }}" role="button">Learn More</a>
`maybeGuid` function in bcc-sage prevented guid links to other domains (from imported content) perhaps we can look at that.

2019-02-01 18:26 UTC, bdolor commented on resources/views/partials/front-page-cards.blade.php
> +        <meta itemprop="image" content="{!! get_the_post_thumbnail_url($get_right_card_id) !!}"/>
`getThumbUrl` in bcc-sage guaranteed a url of at least a default image.

2019-02-01 21:24 UTC, alex-418 commented on resources/views/partials/front-page-cards.blade.php
> +        <meta itemprop="image" content="{!! get_the_post_thumbnail_url($get_right_card_id) !!}"/>
Added a modified version of getThumbUrl via https://github.com/BCcampus/open-sage/pull/46/commits/bedc298c11b2e52b04ae3d7edcd2077a165b3df3

2019-02-02 00:01 UTC, bdolor approved these changes

2019-02-02 00:01 UTC, merged